version: "3.3"
services:
  master:
    image: my_dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_IP=master
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    cap_add:
      - NET_ADMIN
  spark-worker-1:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8081:8081'
    cap_add:
      - NET_ADMIN
  spark-worker-2:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8082:8082'
    cap_add:
      - NET_ADMIN
  spark-worker-3:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8083:8083'
    cap_add:
      - NET_ADMIN
  spark-worker-4:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8084:8084'
    cap_add:
      - NET_ADMIN
  spark-worker-5:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8085:8085'
    cap_add:
      - NET_ADMIN
  spark-worker-6:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8086:8086'
    cap_add:
      - NET_ADMIN

  spark-worker-7:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8087:8087'
    cap_add:
      - NET_ADMIN

  spark-worker-8:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8088:8088'
    cap_add:
      - NET_ADMIN
  spark-worker-9:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8089:8089'
    cap_add:
      - NET_ADMIN
  spark-worker-10:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8090:8090'
    cap_add:
      - NET_ADMIN
  spark-worker-11:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8091:8091'
    cap_add:
      - NET_ADMIN
  spark-worker-12:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8092:8092'
    cap_add:
      - NET_ADMIN
  spark-worker-13:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8093:8093'
    cap_add:
      - NET_ADMIN
  spark-worker-14:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8094:8094'
    cap_add:
      - NET_ADMIN
  spark-worker-15:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8095:8095'
    cap_add:
      - NET_ADMIN
  spark-worker-16:
    image: my_dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/mounted-data
      - type: bind
        source: -conf/log4j.properties
        target: /opt/bitnami/spark/cond/log4j.properties
    ports:
      - '8096:8096'
    cap_add:
      - NET_ADMIN

